services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "4321:4321"
    container_name: ProxyAppWeb
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
