services:
  database:
    image: postgres
    ports:
      - "5433:5432"
    container_name: ProxyAppDB
    environment:
      POSTGRES_PASSWORD: W1909
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ProxyAppApi
    links: 
      - database
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/app
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "4321:4321"
    container_name: ProxyAppWeb
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
volumes: 
  postgres-data:  
